ALTER DATABASE scratch_community CHARACTER SET = utf16 COLLATE = utf16_unicode_ci;

DROP TABLE Posts;

CREATE table Posts(
ThreadID VARCHAR(32) NOT NULL,
PostID INT(8) NOT NULL PRIMARY KEY,
PostNumber INT(8) NOT NULL,
Timestamp VARCHAR(30) CHARACTER SET utf16 NOT NULL,
ContentNoHTML TEXT CHARACTER SET utf16 NOT NULL,
ContentHTML TEXT CHARACTER SET utf16 NOT NULL,
User VARCHAR(32) CHARACTER SET utf16 NOT NULL,
PostCount VarChar(32) CHARACTER SET utf16,
Edited VARCHAR(8) NOT NULL,
EditDate VarChar(16) CHARACTER SET utf16,
SignatureNoHTML TEXT CHARACTER SET utf16,
SignatureHTML TEXT CHARACTER SET utf16
);

LOAD DATA LOCAL INFILE '/Users/jeffstern/Box\ Sync/scratchcollab/posts-new.csv' INTO TABLE Posts CHARACTER SET utf16 FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';
